import {
  Atom,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  Building2,
  Calculator,
  CheckCircle,
  Cloud,
  CreditCard,
  Database,
  DollarSign,
  Eye,
  FileCode,
  Folder,
  Gamepad2,
  Globe,
  Infinity as InfinityIcon,
  Layers,
  type LucideIcon,
  Map as MapIcon,
  Moon as MoonIcon,
  Plane,
  Puzzle,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  Shield,
  Star,
  Target,
  TestTube,
  Trophy,
  Users,
  Zap,
} from 'lucide-react'

// Icon mapping for metrics and achievements
// Replace emoji strings in data with these keys
export const metricIcons: Record<string, LucideIcon> = {
  // Common metrics
  rocket: Rocket,
  trophy: Trophy,
  bot: Bot,
  zap: Zap,
  globe: Globe,
  users: Users,
  database: Database,
  folder: Folder,
  shield: Shield,
  target: Target,
  dollar: DollarSign,
  star: Star,
  search: Search,
  map: MapIcon,
  cloud: Cloud,
  refresh: RefreshCw,
  eye: Eye,
  puzzle: Puzzle,
  book: BookOpen,
  building: Building2,
  calculator: Calculator,
  card: CreditCard,
  plane: Plane,
  brain: Brain,
  code: FileCode,
  layers: Layers,
  check: CheckCircle,
  chart: BarChart3,
  test: TestTube,
  atom: Atom,
  scale: Scale,

  // Achievement icons
  planet: Globe,
  galaxy: Star,
  gamepad: Gamepad2,
  moon: MoonIcon,
  infinity: InfinityIcon,
}

// Helper to get icon component by key
export function getMetricIcon(key: string): LucideIcon {
  return metricIcons[key] || Star
}
